[DRAFT] #98 文化祭オンライン展示
afes-website/back pull request #102
Opened 2020-10-04 14:06 UTC by Takeno-hito

resolve: #98 

何がお困りかというとテストがうまく使いこなせない、そこをどう解決するか決まったらもうprに成り代わります

2020-10-06 02:03 UTC, Takeno-hito commented
READY FOR REVIEW

2020-10-07 12:53 UTC, su8ru requested changes

2020-10-07 12:53 UTC, su8ru commented on app/Http/Controllers/DraftController.php
> +            $drafts->where('user_id', $request->user()->id);
komari

```suggestion
            $drafts->where('exh_id', $request->user()->id);
```

2020-10-07 12:54 UTC, su8ru commented on app/Http/Controllers/DraftController.php
> +            $drafts->where('user_id', $request->user()->id);
テスト不足～～～～

2020-10-08 09:10 UTC, su8ru commented
drafts に対して filter をかけたときに、当てはまるものが無かったときに全部返ってくるの、仕様？

ちょっと困る

2020-10-08 09:22 UTC, su8ru commented
> drafts に対して filter をかけたときに、当てはまるものが無かったときに全部返ってくるの、仕様？
> 
> ちょっと困る
> 
> ![image](https://user-images.githubusercontent.com/33474143/95438702-9fbfff00-0991-11eb-999a-a091a385b3ed.png)

待て待て、そもそも filter されてなくないか（存在する id でもだめ）

2020-10-15 22:30 UTC, su8ru submitted a review, later dismissed
テストの穴はありそうだけど

2020-10-15 23:08 UTC, ibuki2003 requested changes
testはもういいや…別issueでなおしたいね(永遠に治らないやつ…)

2020-10-15 23:08 UTC, ibuki2003 commented on database/migrations/2020_09_27_105115_create_drafts_table.php
> +            $table->bigIncrements('id');
incrementsを避けた？それともコピペもとがこれだった？(incrementsでよくない？)

2020-10-15 23:08 UTC, ibuki2003 commented on database/migrations/2020_10_05_232231_add_category_to_exh.php
> +            //
drop忘れ？わざとならthrowしよう

2020-10-16 00:04 UTC, Takeno-hito commented on app/Http/Controllers/DraftController.php
> +        if($request->user()->has_permission('teacher')) {
両方持ってる場合は両方同時にapproveになるんじゃないかなあと思ったんだけど、むしろ片方だけに勝手になる方がまずいと思った

2020-10-16 00:06 UTC, su8ru commented on app/Http/Controllers/DraftController.php
> +        if($request->user()->has_permission('teacher')) {
多分両方が正解だろなぁ

2020-10-16 00:10 UTC, ibuki2003 commented on app/Http/Controllers/DraftController.php
> +        if($request->user()->has_permission('teacher')) {
よく考えるとそうですね はい

2020-10-16 01:40 UTC, su8ru commented on app/SlackNotify.php
> +            "text" => "{$user_name} has {$action} article {$exhibition->id}",
Slack notify 全く試してないや

2020-10-16 03:35 UTC, Takeno-hito commented on app/SlackNotify.php
> +            "text" => "{$user_name} has {$action} article {$exhibition->id}",
ExhibitionのNotify、そもそも使われてませんでした…(追加してきます)

2020-10-16 03:52 UTC, Takeno-hito commented
🛫

2020-10-16 03:55 UTC, su8ru approved these changes

2020-10-16 03:56 UTC, ibuki2003 commented on app/Http/Controllers/ExhibitionController.php
> +            'type' => ['string', 'regex:/^(normal|frontier|stage)$/'],
あの

2020-10-16 04:05 UTC, Takeno-hito commented
🛫 2️⃣

2020-10-16 04:20 UTC, Takeno-hito commented
🛫 3️⃣

2020-10-16 04:21 UTC, su8ru approved these changes

2020-10-16 04:27 UTC, ibuki2003 approved these changes

2020-10-16 04:28 UTC, merged