#141 すべての Test で actingAs を使うようにした
afes-website/back pull request #142
Opened 2021-03-05 05:53 UTC by Takeno-hito

resolve: #141

- test: add multiple user factory types
- test: refactor: use User factory in draft test
- test: to check 403 in draft_public
- test: eliminate authjwt and use actingAs

2021-03-05 06:03 UTC, ibuki2003 requested changes
AuthJwt::getTokenをprivateにしてほしいです もはや外で使われていないため

2021-03-06 05:52 UTC, su8ru approved these changes
IMSL (I'm so sleepy)

2021-03-06 05:52 UTC, ibuki2003 approved these changes

2021-03-06 05:53 UTC, merged

2021-03-06 05:54 UTC, Takeno-hito commented
IMSL2 (I'm so sleepy too)