外部キー制約を追加
afes-website/back pull request #146
Opened 2021-03-12 14:14 UTC by ibuki2003

した

2021-03-12 14:15 UTC, ibuki2003 commented
参考画像
![image](https://user-images.githubusercontent.com/28347743/110951785-cba04000-8388-11eb-8a6c-88a9f204df80.png)

2021-03-12 14:16 UTC, su8ru approved these changes
`writer_users` と `admin_users` 懐かしい

2021-03-13 03:25 UTC, Takeno-hito requested changes

2021-03-13 03:25 UTC, Takeno-hito commented on database/migrations/2021_03_12_223739_add_foreign_constraint.php
> +        Schema::table('draft_comments', function (Blueprint $table) {
これ、draft_commentとauthorの紐づけは要らないんですか

2021-03-13 03:26 UTC, ibuki2003 commented on database/migrations/2021_03_12_223739_add_foreign_constraint.php
> +        Schema::table('draft_comments', function (Blueprint $table) {
見落としてました>< 夜やる

2021-03-13 09:43 UTC, ibuki2003 commented
![image](https://user-images.githubusercontent.com/28347743/111026105-e5469380-842b-11eb-90e3-19e3572c8c66.png)

2021-03-13 10:02 UTC, su8ru approved these changes

2021-03-13 11:00 UTC, su8ru approved these changes

2021-03-13 11:40 UTC, Takeno-hito approved these changes

2021-03-13 11:40 UTC, merged

2021-03-13 12:03 UTC, Takeno-hito commented on database/migrations/2021_03_12_223739_add_foreign_constraint.php
> +        Schema::table('exhibitions', function (Blueprint $table) {
完全にスルーしてたけどExhibitionがdraftIdを持つことは保証されていないです