テストにmysqlを使用
afes-website/back pull request #154
Opened 2021-03-23 13:03 UTC by ibuki2003

fix #151, #153

2021-03-24 09:01 UTC, Takeno-hito approved these changes

2021-03-24 09:13 UTC, Takeno-hito reviewed
factoryの所に userCreate()みたいなのって使えないの?流石に無理?

2021-03-24 09:15 UTC, ibuki2003 commented
(何言ってるかよくわからないながら解釈したけど、)factoryとしてはあるべきじゃなくない? やるとしてラッパを置くくらい

2021-03-24 09:16 UTC, Takeno-hito commented
testの本体の部分にtest自体には関係のないuserを作成してわざわざ代入する、って処理を毎回書くのは面倒だしちょっと見づらいんじゃないんかなぁ、って少し思っている所でございます

2021-03-24 09:17 UTC, ibuki2003 commented
factoryの中に書くべきじゃないので他にファイルを作るのがよさそう 私は力尽きてもうテストコードにはしばらく触りたくないのでやるならやってください おねがいします

2021-03-24 13:50 UTC, su8ru approved these changes
1つの Pull Request に紐付いた Issue 数ランキング

第 2 位 :tada:

2021-03-24 14:46 UTC, Takeno-hito approved these changes

2021-03-24 14:49 UTC, Takeno-hito requested changes
testComment で 500 が出る事があるみたいです

2021-03-24 14:54 UTC, Takeno-hito reviewed
draft commentのcontentがstring型になってるのが原因みたいです

2021-03-27 00:17 UTC, Takeno-hito requested changes
字数制限突破したコメントが来た時500が来ませんか

2021-03-27 00:18 UTC, ibuki2003 commented
それはたしかに問題なんだけどこのPRではない気がしませんか

2021-03-27 00:34 UTC, Takeno-hito commented
https://github.com/afes-website/back/blob/d17f5ceda7525907b47c0707616aa5eab3774426/database/migrations/2020_10_26_072735_change_content_column_in_draft.php

これと同じノリで一緒になおして頂けたりしませんか content にカラムのtypeを変更するだけで良いと思うし

2021-03-27 02:56 UTC, Takeno-hito approved these changes

2021-03-27 05:33 UTC, su8ru approved these changes

2021-03-27 05:35 UTC, merged